version: "3.8"

x-environment: &environment
  PHP_VERSION: ${PHP_VERSION:-8.2.6}

services:
  phpe-debian:
    build: docker/linux/debian
    container_name: phpe-debian
    working_dir: /home/phpe
    environment:
      <<: *environment
    volumes:
      - .:/home/phpe
  phpe-windows:
    build: docker/windows/ltsc2022
    container_name: phpe-windows
    working_dir: c:\phpe
    environment:
      <<: *environment
    volumes:
      - .:c:\phpe
